#if !canImport(ObjectiveC)
import XCTest

extension EasyTextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EasyTextTests = [
        ("testExample", testExample),
    ]
}

extension TextSliceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextSliceTests = [
        ("testCount", testCount),
        ("testDescription", testDescription),
        ("testEndIndex", testEndIndex),
        ("testFirst", testFirst),
        ("testLast", testLast),
        ("testMakeIterator", testMakeIterator),
        ("testStartIndex", testStartIndex),
        ("testSubscript", testSubscript),
        ("testSubscriptRange", testSubscriptRange),
    ]
}

extension TextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextTests = [
        ("testCount", testCount),
        ("testDescription", testDescription),
        ("testEndIndex", testEndIndex),
        ("testFirst", testFirst),
        ("testLast", testLast),
        ("testMakeIterator", testMakeIterator),
        ("testStartIndex", testStartIndex),
        ("testSubscript", testSubscript),
        ("testSubscriptRange", testSubscriptRange),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EasyTextTests.__allTests__EasyTextTests),
        testCase(TextSliceTests.__allTests__TextSliceTests),
        testCase(TextTests.__allTests__TextTests),
    ]
}
#endif
